### ISSUE TITLE
Cannot use multi-threaded mode on MacBook Pro M1 Max

### ISSUE THREAD

**Issue by biga94** [alexchwong/SpliceWiz#54]
Hey there,
As I try to build the reference using buildRef() function, I cannot use multi-threaded mode even though I've installed libomp.
The warning is:

`fstcore package v0.9.14
(OpenMP was not detected, using single threaded mode)`

Do you know how to deal with this?

Best,

DB

**Comment by alexchwong** [comment]
Hi @biga94 ,

OpenMP needs to be installed on your system. You can install this via brew (instructions as per readme page).

Multi-threaded tabular data processing occurs via the fst / data.table R package functions; otherwise reference building is only single-threaded. OpenMP is required for multi-threaded BAM processing.

**Comment by biga94** [comment]
Dear @alexchwong, thank you for your response.
I forgot to mention that libomp was already installed on my computer. Also, I tried to modify the Makevars file, as suggested on Stackoverflow and others, but nothing changed.
Do you have any other suggestion?

Best,
DB

**Comment by alexchwong** [comment]
Whether fst runs in single or multi-threaded mode doesn't matter much to performance w.r.t. SpliceWiz. If you wish, you could try removing fst / fstcore and re-installing these from source? These packages enable OpenMP at compilation time, so you need to have installed libomp prior to installing fst.

What is the result for the following?

> library(SpliceWiz)
> print(SpliceWiz:::Has_OpenMP())

**Comment by biga94** [comment]
I've tried also to re-install fst / fstcore from source, as suggested on another thread.
As output I have:

`> library(SpliceWiz)
Loading required package: NxtIRFdata
SpliceWiz package loaded with 5 threads
Use setSWthreads() to set the number of SpliceWiz threads
> print(SpliceWiz:::Has_OpenMP())
[1] 0 `

So I guess OpenMP is still not detected.

**Comment by alexchwong** [comment]
Fst in single thread mode is deliberate in `buildRef` because extensive testing showed that using multiple threads made no difference. Fst facilitated fast i/o of data frames of the order of 10-100kb. In essence buildRef does not use multi-threading, and the function should run in the order of ~10 minutes. A typical user will only need to run this once.

Multi-threading is implemented primarily in the `processBAM()` function as this is the typical bottleneck in analysis. It is also an option in `collateData()` but unless you have a lot of RAM and a large number of samples to process, I suggest you run `collateData()` using 1 thread (it can consume 8-16 Gb per thread depending on complexity of the transcriptome in your samples).
